# Make sure to fill in your spotify client_secret information
spotify_token = "BQDgtesy-c5ZY3GLXcFjX7pcq7iMNEKdSXoM1_l7XUwUBRSuTpNVcwZuLrMQMxKpmkxXvbyDWDfJ1vKnOs-dOr1ccjgm6LnO4igNxqMqSQndU6iHhdNcv1CveMnqaEcI0__VK4fUQxpMX8rXoT2ynXRfMl1jWrsW74h0K13Qebp9TEmE1Q"
spotify_user_id = "taylorheil"
